apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demoapp-ingress
  namespace: default
spec:
  ingressClassName: cilium
  rules:
  - host: demoapp.apps.aznpiplatops.az.ga.afginc.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  demoapp
            port:
              name: http
---              
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: demoapp
spec:
  selector:
    app: demoapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: demoapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      name: demoapp
      labels:
        app: demoapp
    spec:
      containers:
        - name: demoapp
          image: nexus.gaig.com:5500/pcf/platform/flask-app-demo:1
          ports:
            - containerPort: 5000
              name: http
          # env:
          # - name: NODE_NAME
          #   valueFrom:
          #     fieldRef:
          #       fieldPath: spec.nodeName
          # - name: POD_NAME
          #   valueFrom:
          #     fieldRef:
          #       fieldPath: metadata.name                
          # - name: POD_NAMESPACE
          #   valueFrom:
          #     fieldRef:
          #       fieldPath: metadata.namespace
          # - name: POD_IP
          #   valueFrom:
          #     fieldRef:
          #       fieldPath: status.podIP
          # - name: POD_SERVICE_ACCOUNT
          #   valueFrom:
          #     fieldRef:
          #       fieldPath: spec.serviceAccountName
          # resources:
          #   limits:
          #     cpu: "1"
          #     memory: "512Mi"
          #   requests:
          #     cpu: "0.5"
          #     memory: "256Mi"
      # serviceAccountName: pod-info