apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demoapp-ingress
  namespace: default
spec:
  ingressClassName: cilium
  rules:
  - host: demoapp.apps.aznpiplatops.az.ga.afginc.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  demoapp
            port:
              name: http
---              
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: demoapp
spec:
  selector:
    app: demoapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: demoapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      name: demoapp
      labels:
        app: demoapp
    spec:
      containers:
        - name: demoapp
          image: nexus.gaig.com:5500/platops/python-docker-demo:v1
          ports:
            - containerPort: 5000
              name: http
          resources:
            limits:
              cpu: "0.5"
              memory: "256Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
      # serviceAccountName: pod-info