apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simplego-ingress
  namespace: default
spec:
  ingressClassName: cilium
  rules:
  - host: simplego.apps.aznpiplatops.az.ga.afginc.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  pod-info
            port:
              name: http
---              
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: pod-info
spec:
  selector:
    app: pod-info
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: pod-info
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-info
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-info
  template:
    metadata:
      name: pod-info
      labels:
        app: pod-info
    spec:
      containers:
        - name: pod-info
          image: ghcr.io/ssanden-gaig/sample-go:v1.1
          ports:
            - containerPort: 8080
              name: http
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name                
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
      serviceAccountName: pod-info